//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : DataBase.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//
package Core;

import java.sql.*;



public class DataBase {
	private Statement stmt;
	private Connection conn;
	
	public void connect(String dbName, String user, String pass) throws SQLException {
	    conn = DriverManager.getConnection("jdbc:mysql://localhost:8888/" + dbName, user, pass); 
		stmt = conn.createStatement(); 
	}
	
	public DataBase() {
		stmt = null;
		conn = null;
	}
	
	public Statement getStatment() {
		return stmt;
	}
	
	public void insert(String tableName,  Object obj) throws SQLException {
		String sqlquery = "insert into " + tableName + " values (" + (new Integer(obj.hashCode()).toString())+obj.toString() + ");";
		System.out.println(sqlquery);
		stmt.executeUpdate(sqlquery);
		
		

	}
	
	public ResultSet  select(String tableName, String cols, String cond) throws SQLException {
		String sqlSelect = "select "+ cols + " From "+ tableName + " where " +cond +";";
		System.out.println(sqlSelect);
		return stmt.executeQuery(sqlSelect);
	}
	
	public void delete(String tableName, String col, String value) throws SQLException
	{
		String sqlDelete = "delete from "+ tableName + " where "+ col + " = " + value + ";";
		stmt.executeUpdate(sqlDelete);
	}
}
