//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : FilmScienceFiction.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//

package Core;


public class FilmScienceFiction extends Film {
	public final int type = 3;

	
	
	public FilmScienceFiction(String titre, Realisateur reali, double prx) {
		super(titre, reali, prx);

	}



	@Override
	public int getType() {
		
		return type;
	}
	public int hashCode()
	{
		return super.hashCode()+ (31 *type);
	}
	public String toString()
	{
		return super.toString() + "'Science Fiction',"+super.getRealisteur().hashCode();
	}
	
}
