//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : FilmRomance.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//

package Core;


public class FilmRomance extends Film {
	private final int type = 1;

	
	
	public FilmRomance(String titre, Realisateur reali, double prx) {
		super(titre, reali, prx);
	}



	@Override
	public int getType() {
		return type;
	}
	
	public int hashCode()
	{
		return super.hashCode()+ (31 *type);
	}
	
	public String toString()
	{
		return  super.toString() + "'Romance',"+super.getRealisteur().hashCode();
	}
	
}
