//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : FilmAction.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//
package Core;



public class FilmAction extends Film {
	private final int type= 2;
	
	FilmAction(String titre,Realisateur r, double prx)
	{
		super(titre,r,prx);
	}
	public int getType()
	{
		return type;
	}
	public int hashCode()
	{
		return super.hashCode()+ (31 *type);
	}
	public String toString()
	{
		return  super.toString() + "'Action',"+super.getRealisteur().hashCode();
	}
}
