//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : Realisateur.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//

package Core;


public class Realisateur {
	private String nom;
	private String prenom;
	public Realisateur() {
	nom = null;
	prenom = null;
	}
	
	public Realisateur(String nom, String prenom) {
	this.nom = nom;
	this.prenom = prenom;
	}
	
	public void setNom(String nom) {
		this.nom = nom;
	}
	
	public String getNom() {
		return nom;
	}
	
	public void setPrenom(String pren) {
		prenom = pren;
	}
	
	public String getPrenom() {
		return prenom;
	}
	
	public String toString() {
		return ",'"+nom + "','" + prenom+"'";
	
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nom == null) ? 0 : nom.hashCode());
		result = prime * result + ((prenom == null) ? 0 : prenom.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Realisateur other = (Realisateur) obj;
		if (nom == null) {
			if (other.nom != null)
				return false;
		} else if (!nom.equals(other.nom))
			return false;
		if (prenom == null) {
			if (other.prenom != null)
				return false;
		} else if (!prenom.equals(other.prenom))
			return false;
		return true;
	}
	
}
