//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SellManager.java
//  @ Date : 1/23/2016
//  @ Author : 
//
//
package Core;
import java.sql.*;

public class SellManager
{
	public DataBase clubDB;
	
	
	public SellManager() throws SQLException
	{
		clubDB = new DataBase();
		clubDB.connect("clubvideo", "root", "");
	}
	public void vend(Chariot commande) throws SQLException
	{
		int sz = sz=commande.films.size();
		for(int id_Vente= getNumberOfSells()  ,i = 0;i < sz; ++i)
		{
			String sqlQr = "insert into Vente values(" +( new Integer(commande.films.elementAt(i).hashCode()).toString())
					        + ","+id_Vente+","+ commande.total+")";
			clubDB.getStatment().executeUpdate(sqlQr);
			
		}

		
	}
	
	public int getNumberOfSells() throws SQLException
	{
		String sql = "select * from Vente";
		ResultSet s =  clubDB.getStatment().executeQuery(sql);
		int sz = 0;
		while(s.next())
			sz++;
		return sz;
	}
}
