//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Club Video
//  @ File Name : StockManager.java
//  @ Date : 1/17/2016
//  @ Author : Chedy Najjar
//
//

package Core;

import java.sql.*;


public class StockManager {
	private DataBase clubDB;
	
	public void addFilm(Film film)throws SQLException {
		clubDB.insert("Film", film);
	}
	
	public void removeFilm(int id_film) throws SQLException {
		clubDB.delete("Film","id_film" , new Integer(id_film).toString());
	}
	
	public ResultSet filterFilm(String col, String value)  throws SQLException{
		
		return clubDB.select("Film", "titre,prix,type", col + " = " + value);
	
	}
	
	public StockManager() throws SQLException {
		clubDB = new DataBase();
		clubDB.connect("clubvideo", "root", "");
	}
	
	public void addRealisateur(Realisateur r) throws SQLException
	{
		clubDB.insert("Realisateur", r);
	}
	
	public void removeRealisateur(int id_rea) throws SQLException {
		clubDB.delete("Realisateur","id_realisateur" , new Integer(id_rea).toString());
		clubDB.delete("Film", "id_realisateur",  new Integer(id_rea).toString());
	}
	
	public ResultSet getAllFilms() throws SQLException
	{
		String sqlQuery = "select * from Film";
		return clubDB.getStatment().executeQuery(sqlQuery);
	}
	public ResultSet getAllFilms(String cols) throws SQLException
	{
		String sqlQuery = "select "+ cols+ " from Film";
		return clubDB.getStatment().executeQuery(sqlQuery);
	}
	
	public ResultSet getAllRealisateur() throws SQLException
	{
		String sqlQuery = "select *from Realisateur";
		return clubDB.getStatment().executeQuery(sqlQuery);
	}
}
